---
title: "Untitled"
output: html_document
date: "2026-01-18"
---
Access to the MICrONS data used in our work requires installation of the Docker platform ([link](https://www.docker.com/get-started/)), along with the Datajoint and docker python packages (both available using pip). The MICrONS NDA access utilities are obtained by cloning the GitHub repository hosted  [here](https://github.com/cajal/microns-nda-access/tree/v8). From this repository, users download the MySQL database container image containing the functional data, using the download link provided in the Database Setup subsection of the README within the previously linked repository. After navigating to the directory containing both the downloaded container image (functional_data_database_container_image_v8.tar), the database can then be initialized by executing `docker load --input functional_data_database_container_image_v8.tar`, followed by `docker-compose up -d database`, from terminal; note that the `docker-compose.yml` file will need to be copied over to the directory as well, if not already there, in order for the `docker-compose` to run successfully.

To extract neural activity traces, users will first need to clone the [MICrONS Phase 3 NDA repository](https://github.com/datajoint/microns_phase3_nda/tree/main/); the full setup instructions can be found in the README in this repository. The Python workflow we used to extract the functional activity data is provided in the accompanying Git repository to this paper ([link](https://github.com/DataSlingers/ClusterQuilting)) in the 'trace_extract.py' file located in the `MICRONS` folder. This script requires imports from the `microns_phase3` submodule included in the `MICrONS Phase 3 NDA repository` Git repository; when running the extraction code within our `ClusterQuilting` repository, the microns_phase3 subfolder should be copied inside the local `MICRONS` directory.

To get the orientation tuning and spatial location information, users will need to extract data from a separate source. The original setup instructions can be found [here](https://tutorial.microns-explorer.org/quickstart_notebooks/01-caveclient-setup.html) for reference. To briefly summarize, the user will need to install the `caveclient` Python package, then set up their own credentials using the link found in the webpage linked above. The code in `get_meta_info.py` located in the `MICRONS` folder of the provided `ClusterQuilting` repository can then be used to get the table of orientation tuning information (requiring the user's access credentials to be edited into the script first.)

[This link](https://tutorial.microns-explorer.org/annotation-tables.html) contains information on the columns of the metadata tables for neuron locations and tuning; specifically for our analysis in the paper, we use the tables listed in the `Automated coregistration` and `Functional properties` subsections. [This link](https://github.com/cajal/microns_phase3_nda/blob/v8/tutorial_notebooks/Using_DataJoint_to_Access_Functional_Data.ipynb) contains general information about the available functional activity data in the MICrONS repository, but is unused for our specific analysis.

